# Lab Assignment Two: Exploring Image Data 

## CS 7324 Fall 2023
## Catherine Magee, Morgan Mote, Luv Patel

### -------------------------------------------------------------------------------------------------------

## Buisness Understanding 

This dataset is constructed from programs made available by NIST (National Institute of Standards and Technology). The data was collected from a total of 43 people and represents each of their handwriting. The dataset consists of 5,620 instances(rows) and 64 features (columns). The purpose of this dataset is to classify peoples handwriting of numerical values by using object recognition. There are many third parties that would benefit from object reconition such as agricuture and security. For exmaple, an agriculture company can use object recognition to detect the difference between a seedling and a dead plant, and in security we can use object recognition to alert staff of a problematic object. Further object reconition can be used for converting text into speech, which helps blind and visually impared individuals. 
    
    

 #### Still need to be answered for buisness. 
Why is this data important? Once you begin modeling, how well would your prediction algorithm need to perform to be considered useful to the identified third parties? Be specific and use your own words to describe the aspects of the data. 

# Data Preparation


## Loading the Dataset: Optical Recognition of Handwritten Digits

### Data comes as pandas dataframe but will be converted to numpy area. 

In [12]:
#pip install ucimlrepo

from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
optical_recognition_of_handwritten_digits = fetch_ucirepo(id=80) 
  
# data (as pandas dataframes) 
X = optical_recognition_of_handwritten_digits.data.features 
y = optical_recognition_of_handwritten_digits.data.targets

# metadata 
print(optical_recognition_of_handwritten_digits.metadata) 
  
# variable information 
print(optical_recognition_of_handwritten_digits.variables) 


      Attribute1  Attribute2  Attribute3  Attribute4  Attribute5  Attribute6  \
0              0           1           6          15          12           1   
1              0           0          10          16           6           0   
2              0           0           8          15          16          13   
3              0           0           0           3          11          16   
4              0           0           5          14           4           0   
...          ...         ...         ...         ...         ...         ...   
5615           0           0           4          10          13           6   
5616           0           0           6          16          13          11   
5617           0           0           1          11          15           1   
5618           0           0           2          10           7           0   
5619           0           0          10          14           8           1   

      Attribute7  Attribute8  Attribute

In [16]:
import numpy as np
X = X.to_numpy()
y = y.to_numpy()

[[ 0  1  6 ...  1  0  0]
 [ 0  0 10 ...  3  0  0]
 [ 0  0  8 ...  0  0  0]
 ...
 [ 0  0  1 ...  6  0  0]
 [ 0  0  2 ... 12  0  0]
 [ 0  0 10 ... 12  1  0]]


In [18]:
n_samples, n_features = X.shape


print(np.sum(~np.isfinite(X)))
print("n_samples: {}".format(n_samples))
print("n_features: {}".format(n_features))

0
n_samples: 5620
n_features: 64


In [34]:
# I think this doesn't work because of poor naming classification

classes = optical_recognition_of_handwritten_digits.class

print(classes)


# This is from the notebook from class. I cannot get our dataset to run these commands. I have been trying for 
# this since tuesday if you figure it out please let me know 

names = lfw_people.target_names
_, h, w = lfw_people.images.shape
n_classes = len(names)
print("n_classes: {}".format(n_classes))
print("Original Image Sizes {} by {}".format(h,w))


SyntaxError: invalid syntax (3484364932.py, line 3)

## Data Preparation (1 points total)

[.5 points] Read in your images as numpy arrays. Resize and recolor images as necessary. 
[.4 points] Linearize the images to create a table of 1-D image features (each row should be one image).   
[.1 points] Visualize several images.

## Data Reduction (6 points total)

[.5 points] Perform linear dimensionality reduction of the images using principal components analysis. Visualize the explained variance of each component. Analyze how many dimensions are required to adequately represent your image data. Explain your analysis and conclusion.
[.5 points] Perform linear dimensionality reduction of your image data using randomized principle components analysis. Visualize the explained variance of each component. Analyze how many dimensions are required to adequately represent your image data. Explain your analysis and conclusion.
[2 points]  Compare the representation using PCA and Randomized PCA. The method you choose to compare dimensionality methods should quantitatively explain which method is better at representing the images with fewer components.  Do you prefer one method over another? Why?
[1 points] Perform feature extraction upon the images using any feature extraction technique (e.g., gabor filters, ordered gradients, DAISY, etc.).
[2 points] Does this feature extraction method show promise for your prediction task? Why? Use visualizations to analyze this questions. For example, visualize the differences between statistics of extracted features in each target class. Another option, use a heat map of the pairwise differences (ordered by class) among all extracted features. Another option, build a nearest neighbor classifier to see actual classification performance.  

 ## Exceptional Work (1 points total)
 
 You have free reign to provide any additional analyses. 
One idea (required for 7000 level students): Perform feature extraction upon the images using DAISY. Rather than using matching on the images with the total DAISY vector, you will instead use key point matching. You will need to investigate appropriate methods for key point matching using DAISY. NOTE: this often requires some type of brute force matching per pair of images, which can be computationally expensive. Does it do better with key point versus not?